### PR TITLE
Remove CircleCI

### PR DESCRIPTION
**Pull request by jkmassel**
Removes the CircleCI configuration – note that the CircleCI configuration file indicates UI tests, but it just tests the empty example project's tests, which doesn't seem that useful, so it's not been moved over.

See https://app.circleci.com/pipelines/github/wordpress-mobile/WordPressUI-iOS/332/workflows/2887f077-5d24-4e26-bd73-0a3780da0fe1/jobs/890 for an example of this.

### CODE REVIEW

**Comment by AliSoftware** [comment]
> note that the CircleCI configuration file indicates UI tests, but it just tests the empty example project's tests, which doesn't seem that useful, so it's not been moved over.

I agree that if it indeed only tests the dummy example test it's quite useless and can be left out.

_(Confession: I first I was like "but wait, there are plenty of test files in `WordPressUITests`"… but then realized that I misread that folder name as if it were `WordPress-UITests` – and thus thought those were UI tests – instead of reading it like `WordPressUI-Tests`… 🤦 )_

---

We should probably use the occasion to remove the useless [Example Unit test](https://github.com/wordpress-mobile/WordPressUI-iOS/blob/e1a6cac09aad4c9c9de9e6f7c7697d9011ee8a70/Example/ExampleTests/ExampleTests.swift) and [Example UI tests](https://github.com/wordpress-mobile/WordPressUI-iOS/blob/e1a6cac09aad4c9c9de9e6f7c7697d9011ee8a70/Example/ExampleUITests/ExampleUITests.swift) files from the repo too btw – though probably via a separate PR.

**Review by AliSoftware — APPROVED** [review]

**Comment by jkmassel** [comment]
> I first I was like "but wait, there are plenty of test files in WordPressUITests"… but then realized that I misread that folder name as if it were WordPress-UITests – and thus thought those were UI tests – instead of reading it like WordPressUI-Tests…

I did exactly the same thing 😅 

Edit: obligatory-ish XKCD: https://xkcd.com/37/

**Comment by jkmassel** [comment]
> We should probably use the occasion to remove the useless Example Unit test and Example UI tests files from the repo too btw – though probably via a separate PR.

This is an interesting one, because I agree with the unit tests, but I don't know of another way to do UI tests on a Pod other than via the example project. WDYT?

**Comment by AliSoftware** [comment]
> This is an interesting one, because I agree with the unit tests, but I don't know of another way to do UI tests on a Pod other than via the example project. WDYT?

I was only suggesting to remove the unit test's empty files, but we can keep the example project if it's needed to run the pod's UI Tests 🙃 

Also maybe we could look at [`s.test_spec`](https://guides.cocoapods.org/syntax/podspec.html#test_spec) as well as [`requires_app_host`](https://guides.cocoapods.org/syntax/podspec.html#requires_app_host) and [`app_host_name`](https://guides.cocoapods.org/syntax/podspec.html#app_host_name) and see if we can use those in the spec to define our UI tests? Never used those myself, but maybe worth looking into.

**Pull request merged**
